# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.CharField(default='a', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='a', max_length=120),
        ),
    ]
